Update README.md
googleapis/nodejs-document-ai pull request #180
Opened 2021-03-10 08:35 UTC by mtannerfors

After hours of debugging `Error: 3 INVALID_ARGUMENT: Request contains an invalid argument.` turns out that apiEndpoint is required if the processor is based in the eu cluster, but not if using the US. Suggest this is added to the Readme.MD.

Thanks for otherwise amazing products and service.

2021-03-12 18:20 UTC, bcoe requested changes
@mtannerfors the sample in the README is automatically generated from here:

https://github.com/googleapis/nodejs-document-ai/blob/master/samples/quickstart.js

(so if you add a comment here, it will be reflected in the README).

Perhaps rather than the note specifically about the EU region, you could link to the list of regions?

https://cloud.google.com/ai-platform/training/docs/regions

2021-03-31 20:46 UTC, bcoe commented
@mtannerfors is this still something you'd like to land? mind making the edit in `samples/quickstart.js`?

2021-04-01 04:18 UTC, mtannerfors commented
> @mtannerfors is this still something you'd like to land? mind making the edit in `samples/quickstart.js`?

Sorry for laggy response, just updated samlples/quickstart.js a suggested.

2021-04-06 23:04 UTC, bcoe commented on README.md
> +// const client = new DocumentProcessorServiceClient({apiEndpoint: 'eu-documentai.googleapis.com'}); // Required if using eu based processor
```suggestion
// You can use processors based in other regions, using the apiEndpoint option:
// const client = new DocumentProcessorServiceClient({apiEndpoint: 'eu-documentai.googleapis.com'}); 
```

2021-04-12 20:13 UTC, telpirion commented
FYI The list of [regions listed for AI Platform](https://github.com/googleapis/python-documentai/pull/108) is not the same as what's available for Document AI.

The current list of regional support for Document AI is [here](https://cloud.google.com/document-ai/docs/regions).

2021-05-20 16:28 UTC, JustinBeckwith commented
Looks like this will be covered in #180 :)

2021-05-20 16:28 UTC, closed without merging